import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { LocalStorage, MemoryStorage, newObjectKey } from './storage.js';
import { AppError } from '../../common/app-error.js';

describe('object keys', () => {
  it('are unguessable and do not collide', () => {
    const a = newObjectKey('sanction order.pdf');
    const b = newObjectKey('sanction order.pdf');
    expect(a).not.toBe(b);
  });

  it('keep a readable tail without keeping the path', () => {
    const key = newObjectKey('Zone A progress — final(2).pdf');
    expect(key).toMatch(/Zone_A_progress.*final_2_\.pdf$/);
    expect(key).not.toContain('—');
  });

  it('strips anything that could climb out of the folder', () => {
    const key = newObjectKey('../../etc/passwd');
    expect(key).not.toContain('..');
    expect(key).not.toContain('/etc/');
    expect(key.endsWith('etc_passwd')).toBe(true);
  });
});

describe('LocalStorage', () => {
  let root: string;
  let storage: LocalStorage;

  beforeAll(async () => {
    root = await mkdtemp(join(tmpdir(), 'ucf-files-'));
    storage = new LocalStorage(root);
  });
  afterAll(async () => {
    await rm(root, { recursive: true, force: true });
  });

  it('round-trips bytes and reports the digest', async () => {
    const bytes = Buffer.from('%PDF-1.7 a sanction order');
    const key = newObjectKey('order.pdf');

    const stored = await storage.put(key, bytes);
    expect(stored.sizeBytes).toBe(bytes.byteLength);
    expect(stored.sha256).toBe(createHash('sha256').update(bytes).digest('hex'));

    expect((await storage.get(key)).equals(bytes)).toBe(true);
    expect((await readFile(join(root, key))).equals(bytes)).toBe(true);
  });

  it('says not-found for a key that was never written', async () => {
    await expect(storage.get('2026/01/nothing.pdf')).rejects.toThrowError(AppError);
  });

  it('removes', async () => {
    const key = newObjectKey('gone.pdf');
    await storage.put(key, Buffer.from('x'));
    await storage.remove(key);
    await expect(storage.get(key)).rejects.toThrowError(AppError);
  });

  /*
   * Keys are generated by the server, so this should be unreachable. It is
   * checked anyway: one traversal here would let an upload overwrite anything
   * the process can write, and "unreachable" is a claim about today's code.
   */
  it('refuses a key that climbs out of the root', async () => {
    await expect(storage.put('../escaped.pdf', Buffer.from('x'))).rejects.toThrowError(AppError);
    await expect(storage.get('../../etc/passwd')).rejects.toThrowError(AppError);
  });
});

describe('MemoryStorage', () => {
  it('behaves the same way', async () => {
    const storage = new MemoryStorage();
    const bytes = Buffer.from('in memory');
    const stored = await storage.put('k', bytes);
    expect(stored.sizeBytes).toBe(bytes.byteLength);
    expect((await storage.get('k')).equals(bytes)).toBe(true);
    await storage.remove('k');
    await expect(storage.get('k')).rejects.toThrowError(AppError);
  });
});
