import type { ReportTable } from './reports.service.js';

/**
 * One table, three formats.
 *
 * The same `ReportTable` becomes JSON, a CSV, or a print-ready page. That is
 * the whole point: a report whose spreadsheet and whose printout disagree
 * about a figure destroys trust in both, and the only way to be sure they
 * agree is for there to be one set of numbers and one renderer.
 *
 * "PDF" is the print-ready page plus the browser's own Save as PDF, the same
 * route the MoM takes. It keeps one HTML template as the single source of the
 * printed output rather than a second layout that drifts.
 */
export function toCsv(table: ReportTable): string {
  const cell = (v: unknown) => {
    const s = v === null || v === undefined ? '' : String(v);
    // Quote everything. A description with a comma in it is the common case,
    // and a spreadsheet that splits one row across two is worse than none.
    return `"${s.replace(/"/g, '""')}"`;
  };

  const lines = [
    [table.title],
    [table.lede],
    [`Generated ${table.generatedAt}`],
    [],
    table.summary.map((s) => `${s.label}: ${s.value}`),
    [],
    table.columns.map((c) => c.label),
    ...table.rows.map((r) => table.columns.map((c) => r[c.key])),
  ];

  return lines.map((line) => line.map(cell).join(',')).join('\r\n');
}

const esc = (v: unknown) =>
  String(v ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

export function toHtml(table: ReportTable, who: string): string {
  const generated = new Date(table.generatedAt);
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>${esc(table.title)}</title>
<style>
  @page { size: A4 landscape; margin: 14mm 12mm; }
  * { box-sizing: border-box; }
  body { font: 11px/1.45 "Segoe UI", system-ui, sans-serif; color: #1D3557; margin: 0; }
  header { border-bottom: 2px solid #1D3557; padding-bottom: 8px; margin-bottom: 14px; }
  .eyebrow { font-size: 8.5px; letter-spacing: 1.6px; text-transform: uppercase; color: #6B7C93; }
  h1 { font-size: 17px; margin: 4px 0 2px; }
  .lede { color: #55657A; font-size: 11px; margin: 0; }
  .meta { margin-top: 6px; font-size: 9.5px; color: #6B7C93; }
  .summary { display: flex; flex-wrap: wrap; gap: 18px; margin: 0 0 12px; padding: 9px 12px;
             background: #F4F7FB; border: 1px solid #DCE4EE; border-radius: 6px; }
  .summary div { min-width: 120px; }
  .summary b { display: block; font-size: 16px; }
  .summary span { font-size: 8.5px; letter-spacing: 1.1px; text-transform: uppercase; color: #6B7C93; }
  table { width: 100%; border-collapse: collapse; }
  th, td { border: 1px solid #DCE4EE; padding: 5px 7px; text-align: left; vertical-align: top; }
  th { background: #EDF2F8; font-size: 9px; letter-spacing: .7px; text-transform: uppercase; }
  td.n, th.n { text-align: right; font-variant-numeric: tabular-nums; }
  tbody tr:nth-child(even) { background: #FAFBFD; }
  footer { margin-top: 12px; font-size: 9px; color: #6B7C93; }
  @media print { .noprint { display: none; } }
  .noprint { margin-bottom: 12px; }
  .noprint button { font: inherit; padding: 6px 12px; border: 1px solid #1D3557; background: #1D3557;
                    color: #fff; border-radius: 6px; cursor: pointer; }
</style></head>
<body>
  <div class="noprint"><button onclick="window.print()">Print or save as PDF</button></div>
  <header>
    <div class="eyebrow">Urban Challenge Fund · Meeting &amp; Action Item Tracker</div>
    <h1>${esc(table.title)}</h1>
    <p class="lede">${esc(table.lede)}</p>
    <div class="meta">Prepared for ${esc(who)} · ${esc(generated.toUTCString())} · figures are scoped to the projects this officer may see, and count only items carried by a circulated MoM.</div>
  </header>

  <div class="summary">
    ${table.summary
      .map((s) => `<div><b>${esc(s.value)}</b><span>${esc(s.label)}</span></div>`)
      .join('')}
  </div>

  <table>
    <thead><tr>${table.columns
      .map((c) => `<th${c.numeric ? ' class="n"' : ''}>${esc(c.label)}</th>`)
      .join('')}</tr></thead>
    <tbody>
      ${
        table.rows.length === 0
          ? `<tr><td colspan="${table.columns.length}">Nothing matches this report’s filters.</td></tr>`
          : table.rows
              .map(
                (r) =>
                  `<tr>${table.columns
                    .map(
                      (c) =>
                        `<td${c.numeric ? ' class="n"' : ''}>${esc(r[c.key] ?? '—')}</td>`,
                    )
                    .join('')}</tr>`,
              )
              .join('')
      }
    </tbody>
  </table>

  <footer>${table.rows.length} row${table.rows.length === 1 ? '' : 's'} · generated by the UCF Meeting &amp; Action Item Tracker.</footer>
</body></html>`;
}
